version: '3.9'

services:
  app:
    build: .
    container_name: faya-nest-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: faya-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 00000000
      MYSQL_DATABASE: fayaport
      MYSQL_USER: root
      MYSQL_PASSWORD: 00000000
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
