version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fayaport-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fayaport-net

  app:
    container_name: fayaport-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - mysql
    networks:
      - fayaport-net

volumes:
  mysql_data:

networks:
  fayaport-net:
    driver: bridge
